import type { Metadata } from "next";
import { Forum } from "next/font/google";
import "./globals.css";
import Header from "@/components/home/header/Header";

// const inter = Inter({ subsets: ["latin"] });

const forum = Forum({
  subsets: ["latin", "cyrillic"],
  variable: "--font-forum",
  weight: "400",
});

export const metadata: Metadata = {
  title: {
    default: "Mvila",
    template: "%s | Mvila",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${forum.variable}`}>
      <body className="bg-mainBg text-[#202020]">
        <Header />
        <main className=" flex flex-col items-center justify-center">
          {children}
        </main>
        <footer>footer</footer>
        {/* <footer className="border border-blue-600">footer</footer> */}
      </body>
    </html>
  );
}
