import type { Metadata } from "next";
import { Forum, Lora } from "next/font/google";
import "../styles/globals.css";
import { NextFontWithVariable } from "next/dist/compiled/@next/font";
import { ModalWindowProvider } from "@/contexts/ModalWindowContext";

// const inter = Inter({ subsets: ["latin"] });

const forum: NextFontWithVariable = Forum({
  subsets: ["latin", "cyrillic"],
  variable: "--font-forum",
  weight: "400",
});

const lora: NextFontWithVariable = Lora({
  subsets: ["latin", "cyrillic"],
  variable: "--font-lora",
});

export const metadata: Metadata = {
  title: {
    default: "Mvila",
    template: "%s | Mvila",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`${forum.variable} ${lora.variable} font-serif`}>
      <body className="flex min-h-screen flex-col bg-mainBg text-[#202020]">
        <ModalWindowProvider>{children}</ModalWindowProvider>
      </body>
    </html>
  );
}
