import type { Metadata } from "next";
import { Forum } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/home/header/Header";
import Footer from "@/components/home/footer/Footer";

// const inter = Inter({ subsets: ["latin"] });

const forum = Forum({
  subsets: ["latin", "cyrillic"],
  variable: "--font-forum",
  weight: "400",
});

export const metadata: Metadata = {
  title: {
    default: "Mvila",
    template: "%s | Mvila",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`${forum.variable}`}>
      <body className="bg-mainBg min-h-screen flex flex-col text-[#202020]">
        {children}
      </body>
    </html>
  );
}
